// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7LuM18b04sCu8_I38RmHCrHHjkHYsVuE',
    appId: '1:507975494476:web:cd755fb196568eded0bde9',
    messagingSenderId: '507975494476',
    projectId: 'course-app-5eda4',
    authDomain: 'course-app-5eda4.firebaseapp.com',
    storageBucket: 'course-app-5eda4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBG8icthOdZwnOz0rOOb6VFmqxlX_ACw',
    appId: '1:507975494476:android:cca1d6173b3b4b7ed0bde9',
    messagingSenderId: '507975494476',
    projectId: 'course-app-5eda4',
    storageBucket: 'course-app-5eda4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCOsgfAQHSyzjH9fl3aRoZRZt2nlyRYdQ',
    appId: '1:507975494476:ios:02c98a7672a0cc5cd0bde9',
    messagingSenderId: '507975494476',
    projectId: 'course-app-5eda4',
    storageBucket: 'course-app-5eda4.appspot.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCOsgfAQHSyzjH9fl3aRoZRZt2nlyRYdQ',
    appId: '1:507975494476:ios:5379773a1752b0b0d0bde9',
    messagingSenderId: '507975494476',
    projectId: 'course-app-5eda4',
    storageBucket: 'course-app-5eda4.appspot.com',
    iosBundleId: 'com.example.courseApp.RunnerTests',
  );
}
